"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob
APP = ['Jazz Piano.py']
DATA_FILES = ['theory.json','incorrect.mp3','correct.mp3','Images/keys.png'] + glob.glob('*.png')
OPTIONS = { 'argv_emulation': True, 'iconfile': 'icon.icns'} # This line adds the icon to your app bundle }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
